
Import('*')

#if not main['HAVE_SPIKE']:
#    print("Not building Downstream, could not find SPIKE")
#    Return()
#
#
SimObject('UpDownBASim.py')

Source('updown_basim.cc')

DebugFlag('UpDownBASim', "Simple simulation of the updown processor")
